USE todo_db
GO	

CREATE TABLE "user" 
(
	id INT PRIMARY KEY IDENTITY(1,1),
	username NVARCHAR(100) NOT NULL UNIQUE,
	email NVARCHAR(255) NOT NULL UNIQUE,
	password_hash VARBINARY(MAX) NOT NULL,
	created_at DATETIME DEFAULT GETDATE()
)

CREATE TABLE "todo_list"
(
	id INT PRIMARY KEY IDENTITY(1,1),
	name NVARCHAR(100) NOT NULL,
	description NVARCHAR(255),
	created_at DATETIME DEFAULT GETDATE() NOT NULL,
)

CREATE TABLE "